# version: "3.2"
# services:
#   rabbitmq:
#     image: rabbitmq:3-management-alpine
#     container_name: 'rabbitmq'
#     ports:
#         - 5672:5672
#         - 15672:15672
#     volumes:
#         - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#         - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
 version: '3'
 services:
    rabbitmq:
        build:
            context: docker/rabbitmq
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - dev-network
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
            - RABBITMQ_DEFAULT_VHOST=/
 networks:
      dev-network:
      driver:





            